### ISSUE TITLE
pdf导出图片无法显示

### ISSUE THREAD

**Issue by YemaoLuo** [imzbf/md-editor-extension#10]
对于某些图片会无法显示，如图所示。
![image](https://github.com/imzbf/md-editor-extension/assets/90177205/6675a0ba-9317-49e7-bec1-4f2a2dcaef1a)
![image](https://github.com/imzbf/md-editor-extension/assets/90177205/caa3da8d-a4f5-48d0-a428-839d827793e2)

**Comment by imzbf** [comment]
是不同源的图片？

**Comment by YemaoLuo** [comment]
![google](https://fonts.gstatic.com/s/i/productlogos/chrome_store/v7/192px.svg)
![baidu](https://www.baidu.com/img/PCtm_d9c8750bed0b3c7d089fa7d55720d6cf.png)

**Comment by YemaoLuo** [comment]
这两行md

**Comment by imzbf** [comment]
最好使用同域下的，或者自己可以设置的资源服务，或者支持跨域的
