### ISSUE TITLE
Emoji 组件中的属性 emojis 好像并没有起到作用。

### ISSUE THREAD

**Issue by lipingshan** [imzbf/md-editor-extension#12]
你好。①Emoji 组件中的属性 emojis 好像并没有起到作用。是写得有问题么？
# 下面是部分代码
```vue
<template #defToolbars>
	<Mark />
	<Emoji :emojis="['🤡','💀']" :selectAfterInsert="false"/>
	<ReadExtension :mdText="text" />
	<ExportPDF :modelValue="text" modalTitle="导出为pdf" height="100%" width="60%" />
</template>
```
# 效果 
和之前没加一样
![image](https://github.com/imzbf/md-editor-extension/assets/44489654/aa6f2fe7-405f-408e-93ff-0b0ddf738e66)

②并且这个表情 也不是在方格的正中央。很明显偏下了。

**Comment by imzbf** [comment]
1. emojis未生效是BUG
2. 内容偏向下面需要你自行检查自己项目的css对它的影响

**Comment by imzbf** [comment]
我在`1.1.1`中修复了它，尝试安装新版本
