### ISSUE TITLE
一个很好的需求

### ISSUE THREAD

**Issue by itianci06** [imzbf/md-editor-extension#14]
### Describe the issue

`
<template #defToolbars>
         <ExportPDF :modelValue="docContent" />
 </template>
`
 
 请问这个 ExportPDF 导出为pdf 组件，我能不能不在编辑器组件内使用，在外部单独使用呢，我并没有在官方文档中找到我需要的，我尝试了一下，不在编辑器组件内使用，但出现报错了。比如我需要一次性导出多个 markdown 文件内容为 pdf 文件。

### Procedure version

4.0.10

**Comment by imzbf** [comment]
这个组件依赖的编辑器的东西的，单独指定不行。

如果你想在别的地方放置导出按钮，可以复制一份源码到你的项目中，它仅依赖了`html2pdf.js`

另外如果想一次性导出多个这个功能在前端做不现实，因为导出意味着所有的都需要有对应的html节点在页面中，且所有的内容样式展示正确才行，批量导出建议在服务端去做
