### ISSUE TITLE
ExportPDF 导出pdf时候 文字丢失，我用html2canvas通用如此

### ISSUE THREAD

**Issue by MTTTM** [imzbf/md-editor-extension#15]
## cmd内容为以下时候，出现导出pdf，活着导出png时候，文字不显示，边框有

`# 欢迎使用 Txt Markdown 编辑阅读器

------

我们理解您需要更便捷更高效的工具记录思想，整理笔记、知识，并将其中承载的价值传播给他人，**Txt Markdown** 是我们给出的答案 —— 我们为记录思想和分享知识提供更专业的工具。 您可以使用 Txt Markdown：

> * 整理知识，学习笔记
> * 发布日记，杂文，所见所想
> * 撰写发布技术文稿（代码支持）
> * 撰写发布学术论文（LaTeX 公式支持）

- [ ] 支持以 PDF，PNG 格式导出文稿
- [ ] 改进 本地txt 文件读取算法，使用局部渲染技术提高渲染效率
- [ ] 通过登陆解决导出图片空白问题
- [x] 新增 Todo 列表功能
- [x] 修复 LaTex 公式渲染问题
- [x] 新增 LaTex 公式编号功能

`

**Comment by imzbf** [comment]
<img width="930" alt="image" src="https://github.com/imzbf/md-editor-extension/assets/37092006/fc8da752-06a0-43a5-a4e8-e2b71e186ecd">
上面的meo没人导出好像没有出现你描述的问题，是否是文章中有图片导出时没有正确导出图片？

**Comment by imzbf** [comment]
> <img alt="image" width="930" src="https://private-user-images.githubusercontent.com/37092006/296641284-fc8da752-06a0-43a5-a4e8-e2b71e186ecd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUyODczMDIsIm5iZiI6MTcwNTI4NzAwMiwicGF0aCI6Ii8zNzA5MjAwNi8yOTY2NDEyODQtZmM4ZGE3NTItMDZhMC00M2E1LWE0ZTgtZTJiNzFlMTg2ZWNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE1VDAyNTAwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNjMDllMWI5MzAzNjcyZThmZDNhNGY5MWEwMzEwMjJhNDNjMWMyZTQzMjFkZTNhZjkzOWVmMTA0ZWUwMTY2NWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GielbCzH6uGX8IX63yKGYSAaIu2IXd2HLqkP6PSI8OI"> 上面的demo没人导出好像没有出现你描述的问题，是否是文章中有图片导出时没有正确导出图片？

**Comment by imzbf** [comment]
<img alt="image" width="930" src="https://private-user-images.githubusercontent.com/37092006/296641284-fc8da752-06a0-43a5-a4e8-e2b71e186ecd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUyODczMDIsIm5iZiI6MTcwNTI4NzAwMiwicGF0aCI6Ii8zNzA5MjAwNi8yOTY2NDEyODQtZmM4ZGE3NTItMDZhMC00M2E1LWE0ZTgtZTJiNzFlMTg2ZWNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE1VDAyNTAwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNjMDllMWI5MzAzNjcyZThmZDNhNGY5MWEwMzEwMjJhNDNjMWMyZTQzMjFkZTNhZjkzOWVmMTA0ZWUwMTY2NWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GielbCzH6uGX8IX63yKGYSAaIu2IXd2HLqkP6PSI8OI"> 上面的demo没人导出好像没有出现你描述的问题，是否是文章中有图片导出时没有正确导出图片？

**Comment by MTTTM** [comment]
> <img alt="image" width="930" src="https://private-user-images.githubusercontent.com/37092006/296641284-fc8da752-06a0-43a5-a4e8-e2b71e186ecd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUyODczMDIsIm5iZiI6MTcwNTI4NzAwMiwicGF0aCI6Ii8zNzA5MjAwNi8yOTY2NDEyODQtZmM4ZGE3NTItMDZhMC00M2E1LWE0ZTgtZTJiNzFlMTg2ZWNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE1VDAyNTAwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNjMDllMWI5MzAzNjcyZThmZDNhNGY5MWEwMzEwMjJhNDNjMWMyZTQzMjFkZTNhZjkzOWVmMTA0ZWUwMTY2NWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GielbCzH6uGX8IX63yKGYSAaIu2IXd2HLqkP6PSI8OI"> 上面的demo没人导出好像没有出现你描述的问题，是否是文章中有图片导出时没有正确导出图片？

已解决，是因为第三方库的css影响

**Comment by MTTTM** [comment]
已解决，是因为第三方库的css影响
