### ISSUE TITLE
ExportPDF 添加theme无效，还是默认的default-theme

### ISSUE THREAD

**Issue by MTTTM** [imzbf/md-editor-extension#16]
ExportPDF 添加theme无效

阅读源码后好像问题在于MdPreview组件的主题是用provide传递，但是ExportPDF是用props

&lt;MdEditor
    ref=&quot;editorRef&quot;
    theme=&quot;github&quot;
    previewTheme=&quot;github&quot;
  &gt;
    &lt;template #defToolbars&gt;
      &lt;ExportPDF :modelValue=&quot;contentStore.content&quot;  theme=&quot;github&quot; previewTheme=&quot;github&quot;/&gt;
    &lt;/template&gt;
  &lt;/MdEditor&gt;

**Comment by imzbf** [comment]
导出的组件好像并没有考虑这些，后面我给加上

**Comment by imzbf** [comment]
1.2.0优化了它，并且你不需要主动提供`theme`和`previewTheme`就可以
