### ISSUE TITLE
导出PDF功能：在Firefox上代码导出异常

### ISSUE THREAD

**Issue by Arcticn** [imzbf/md-editor-extension#31]
zbf，您好：
使用同一段代码在官网https://imzbf.github.io/md-editor-v3/zh-CN/index 上进行测试
[测试样例.md](https://github.com/user-attachments/files/16044103/default.md)

在火狐127版本上结果如下
![图片](https://github.com/imzbf/md-editor-extension/assets/46252987/b3324153-f4e3-48c2-85a2-f1121d71a29d)

Chromium系浏览器正常导出

**Comment by imzbf** [comment]
是的，html2pdf可能不是最完美的方案，等后面调试看看

该问题与 https://github.com/imzbf/md-editor-extension/issues/30 类似，归类到这个issue下
