### ISSUE TITLE
引入ExportPDF插件后带来的问题

### ISSUE THREAD

**Issue by geedys** [imzbf/md-editor-extension#36]
我的项目情况：
1. electron 31.4.0 + vite 5.4.1 + vue 3.4.38，electron环境下，html中开启了CSP
2. 采用了非cdn方式，参照的 https://github.com/imzbf/md-editor-v3/discussions/294 中的方法
3. 在没有使用这个插件的情况下一切正常。
4. 开启了这个插件后，打开编辑器所在的页面会请求 https://at.alicdn.com/t/c/font_2605852_cmafimm6hot.js 文件
5. 在切换主题时(theme属性)， 会加载 https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.8.0/styles/atom-one-dark.min.css 文件

需求：
1. 我希望不管是否在线的情况下，都不要加载CDN文件。该插件要怎么配置呢？
2. 弹出的导出pdf对话框虽然可以设置width，预览时正常，但是导出的pdf内容宽度并没有变化，导致部分内容被遮挡。
![image](https://github.com/user-attachments/assets/00400303-429f-4e21-a430-ab4d0acaa8e2)

**Comment by imzbf** [comment]
导出的实际情况是根据你在浏览器设置的纸张大小决定的，这种情况你需要设置单行自动换行才行

CDN方面，你设置`noIconfont`了吗

**Comment by geedys** [comment]
> 导出的实际情况是根据你在浏览器设置的纸张大小决定的，这种情况你需要设置单行自动换行才行
> 
> CDN方面，你设置`noIconfont`了吗

CDN方面,我确定已经设置了noIconfont了。此问题的出现仅在使用了ExportPDF插件以后
设置单行自动换行？是有哪个属性吗？自己写css？不是太理解呢。

**Comment by imzbf** [comment]
iconfont是内部的预览组件缺少该属性设置，后面我会调整

是需要自己调整文本超出宽度自动换行的css的，如果不清楚的话，可以去查找一下相关的内容

**Comment by imzbf** [comment]
尝试编辑器^4.19.1和扩展库^1.3.0，ExportPDF组件支持设置`noIconfont`属性

**Comment by geedys** [comment]
imzbf, 你好，编辑器^4.19.1和扩展库^1.3.0后，主题样式切换确实解决了，
但是开启了ExportPDF这个插件后，打开编辑器所在的页面依然会请求 CDN： https://at.alicdn.com/t/c/font_2605852_cmafimm6hot.js 文件
由于我的项目在Electron环境下，开启了CSP，控制台会报错：
![image](https://github.com/user-attachments/assets/9e5267b3-dd6f-41fe-94ab-1b80e3f0f8c9)

**Comment by imzbf** [comment]
需要给ExportPDF组件设置noIconfont属性，就不会去请求外部的链接了

**Comment by geedys** [comment]
> 需要给ExportPDF组件设置noIconfont属性，就不会去请求外部的链接了

感谢， 感谢，刚试了一下，设置了no-iconfont属性后问题解决了，之前没成功， 可能是因为nodel_modules/vite目录下文件缓存导致的。

**Comment by geedys** [comment]
> 需要给ExportPDF组件设置noIconfont属性，就不会去请求外部的链接了

感谢， 感谢，刚试了一下，设置了no-iconfont属性后问题解决了，之前没成功， 可能是因为nodel_modules/vite目录下文件缓存导致的。
