### ISSUE TITLE
导出的pdf 增加页码显示

### ISSUE THREAD

**Issue by webguosai** [imzbf/md-editor-extension#40]
可以给导出的pdf文件，增加页码显示吗
比如pdf有50页，然后在每页的下面，显示 1/50    2/50  这样

**Comment by imzbf** [comment]
好像可以，我增强一下

**Comment by imzbf** [comment]
在2.0.0新增了pdf的设置功能，参考：https://github.com/imzbf/md-editor-extension/blob/main/packages/v3/components/ExportPDF/README.md#set-page-number

你需要安装5.0.0以上版本的编辑器

**Comment by webguosai** [comment]
@imzbf 感谢
