### ISSUE TITLE
Manually trigger exportPDF without adding to toolbar

### ISSUE THREAD

**Issue by DerSimeon** [imzbf/md-editor-extension#41]
Hello, is it possible to manually trigger a PDF Export via the editorRef without adding the exportPDF toolbar component?
If not could you tell me a workaround on how to do it anyway?

**Comment by imzbf** [comment]
I will find time to see if I can expose a trigger

**Comment by DerSimeon** [comment]
Hey @imzbf is there an update to this?

**Comment by imzbf** [comment]
It's available in version 2.1.0. https://github.com/imzbf/md-editor-extension/tree/develop/packages/v3/components/ExportPDF#expose

**Comment by DerSimeon** [comment]
Thank you! Could you tell me what the type for the pdfRef should be?
For Example its ExposeParam for MdEditor

**Comment by imzbf** [comment]
I haven't finalized how to export the types for individual components yet.
