### ISSUE TITLE
emoji在网页缩小为90%后，表情包选择框左右不对称

### ISSUE THREAD

**Issue by liaokaipeng** [imzbf/md-editor-extension#5]
### Describe the issue

emoji在网页缩小为90%后，表情包选择框左右不对称，有点别扭

### Procedure version

谷歌浏览器 （115.0.5790.110）

**Comment by imzbf** [comment]
给个图看看，我缩小了没看出来

**Comment by liaokaipeng** [comment]
![捕获](https://github.com/imzbf/md-editor-v3/assets/37499635/a454a2fc-7c33-4c93-ae57-0fa0adeb0d7a)

**Comment by imzbf** [comment]
![image](https://github.com/imzbf/md-editor-extension/assets/37092006/c7744107-6776-41de-87a5-3a71427c7c18)

尝试一下使用这个扩展组件库中提供的emoji组件
