### ISSUE TITLE
emoji拓展个别表情异常

### ISSUE THREAD

**Issue by YemaoLuo** [imzbf/md-editor-extension#9]
在chrome和edge中均存在此问题。
![image](https://github.com/imzbf/md-editor-extension/assets/90177205/f2fa60d1-3362-46ab-8dd7-236f78897831)

**Comment by imzbf** [comment]
这个没什么办法，每个操作系统都会影响

不过我提供了`emojis`属性，它就是一个表情列表，可以去这里 https://getemoji.com/ 找你想要的图标组成列表

**Comment by YemaoLuo** [comment]
感谢回复

**Comment by lipingshan** [comment]
Emoji 的 emojis 属性设置了之后，好像没有效果呀。
```vue
	<template #defToolbars>
					<Mark />
					<Emoji :emojis="['🤡','💀']" :selectAfterInsert="false"/>
					<ReadExtension :mdText="text" />
					<ExportPDF :modelValue="text" modalTitle="导出为pdf" height="100%" width="60%" />
				</template>
```

**Comment by imzbf** [comment]
> Emoji 的 emojis 属性设置了之后，好像没有效果呀。
> 
> ```
> 	<template #defToolbars>
> 					<Mark />
> 					<Emoji :emojis="['🤡','💀']" :selectAfterInsert="false"/>
> 					<ReadExtension :mdText="text" />
> 					<ExportPDF :modelValue="text" modalTitle="导出为pdf" height="100%" width="60%" />
> 				</template>
> ```

好像是个BUG
